export const categories = [
  { id: "basic-noise", title: "basic noise", gradientFrom: "#7b7979", gradientTo: "#7AA3A0" },
  { id: "musical", title: "musical", gradientFrom: "#4F4090", gradientTo: "#7AA3A0" },
  { id: "ambience", title: "ambience", gradientFrom: "#016D40", gradientTo: "#7AA3A0" },
];

export const sounds = [
  {
    id: "whitenoise",
    title: "white noise",
    categoryId: "basic-noise",
    csdFile: "/sounds/whitenoise/whitenoise.csd",
    description: "White noise is often used to mask other sounds and block distractions. If it sounds too harsh, try other colors.",
    audioFiles: [],
    params: [],
  },
  {
    id: "pinknoise",
    title: "pink noise",
    categoryId: "basic-noise",
    csdFile: "/sounds/pinknoise/pinknoise.csd",
    description: "Pink noise is white noise with less high frequencies, similar to the sound of a waterfall.",
    audioFiles: [],
    params: [],
  },
  {
    id: "waves",
    title: "waves",
    categoryId: "basic-noise",
    csdFile: "/sounds/waves/generativesea.csd",
    description: "Randomly generated waves of noise, inspired by ocean sounds. Blends basic noise with organic movement and a sense of space.",
    audioFiles: [],
    params: [],
  },
  {
    id: "sinesong",
    title: "sine song",
    categoryId: "musical",
    csdFile: "/sounds/sinesong/sinesong.csd",
    description: "Calming harmony as a result of simple algorithmic counterpoint of three sine waves.",
    audioFiles: [],
    params: [],
  },
  {
    id: "mantra",
    title: "mantra",
    categoryId: "musical",
    csdFile: "/sounds/mantra/mantra.csd",
    description: "Blooming chords paired with soft bass and occasional percussive embelishments.",
    audioFiles: [],
    params: [],
  },
  {
    id: "softmachines",
    title: "soft machines",
    categoryId: "ambience",
    csdFile: "/sounds/softmachines/mechanical.csd",
    description: "Calming mechanical noises. Create your own blend of the hum of a fan, airplane cabin or an AC unit.",
    audioFiles: ["acunit.mp3", "fan.mp3", "plane.mp3", "train.mp3"],
    params: [
      { id: "fanLevel", label: "Fan", default: 0.5 },
      { id: "planeLevel", label: "Plane", default: 0.5 },
      { id: "acunitLevel", label: "AC Unit", default: 0.5 },
      { id: "trainLevel", label: "Train", default: 0.5 },
    ],
  },
  {
    id: "forest",
    title: "forest",
    categoryId: "ambience",
    csdFile: "/sounds/forest/forest.csd",
    description: "Wind down with the sound of birds, stream, leaves and wind.",
    audioFiles: ["ambience.mp3", "stream.mp3", "wind.mp3", "leaves.mp3"],
    params: [{ id: "birdLevel", label: "Birds", default: 0.7 },
    { id: "windLevel", label: "Wind", default: 0.5 },
    { id: "streamLevel", label: "Stream", default: 0.6 },
    { id: "rustleLevel", label: "Leaves", default: 0.4 },],
  },
];